#!/bin/bash

# Script to compare RTL output between new compiler and expected RTL files
# This script compares the RTL files generated by the new-compiler
# with expected RTL files from the reference SCLP compiler

set -e  # Exit on any error

# Define compiler paths
NEW_COMPILER="./new-compiler"
EXPECTED_DIR="example-programs/Level-4-valid-rtl"
TEST_DIR="example-programs/Level-4-test-cases"

# Check if new compiler exists
if [ ! -f "$NEW_COMPILER" ]; then
    echo "Error: $NEW_COMPILER not found. Please compile it first."
    exit 1
fi

# Initialize counters
passed=0
failed=0
total=0

# Color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "=========================================="
echo "RTL Comparison Test Suite"
echo "=========================================="
echo ""

# Process all Level-4 test cases
for testfile in "$TEST_DIR"/l4-exmp*.c; do
    if [ -f "$testfile" ]; then
        testname=$(basename "$testfile")
        base_testname="${testname%.c}"
        
        total=$((total + 1))
        
        # Generate RTL output from new compiler
        echo -n "Processing $testname ... "
        
        # Copy test file to current directory temporarily
        cp "$testfile" ./"$testname"
        
        # Run the new compiler with --show-rtl flag
        if ./"$NEW_COMPILER" "$testname" --show-rtl > /dev/null 2>&1; then
            # Check if RTL file was generated
            if [ -f "${testname}.rtl" ]; then
                echo "RTL generated"
                
                # Check if expected RTL file exists (with .correct.rtl suffix)
                # Convert l4-exmpX to l4-exmp-X for matching expected files
                base_for_expected=$(echo "$base_testname" | sed 's/l4-exmp\([0-9]\)/l4-exmp-\1/')
                expected_file="$EXPECTED_DIR/${base_for_expected}.c.correct.rtl"
                if [ -f "$expected_file" ] && [ -s "$expected_file" ]; then
                    # Compare the generated RTL with expected (strip comments before comparing)
                    # Remove comments (anything after ;;) and extra whitespace
                    generated_stripped=$(sed 's/;;.*//' "${testname}.rtl" | sed 's/[[:space:]]*$//')
                    expected_stripped=$(sed 's/;;.*//' "$expected_file" | sed 's/[[:space:]]*$//')
                    
                    if diff -Bw <(echo "$generated_stripped") <(echo "$expected_stripped") > /dev/null 2>&1; then
                        echo -e "${GREEN}✓ PASS${NC}: $testname"
                        passed=$((passed + 1))
                    else
                        echo -e "${RED}✗ FAIL${NC}: $testname (output differs)"
                        failed=$((failed + 1))
                        echo "  First 5 lines of diff:"
                        diff -Bw <(echo "$generated_stripped") <(echo "$expected_stripped") | head -5 | sed 's/^/    /'
                    fi
                else
                    # No expected file or it's empty - this test is not ready yet
                    echo -e "${GREEN}✓ SKIP${NC}: $testname (expected RTL not provided yet)"
                    # Don't count as passed or failed, just informational
                fi
            else
                echo -e "${RED}✗ FAIL${NC}: $testname (RTL file not generated)"
                failed=$((failed + 1))
            fi
        else
            echo -e "${RED}✗ FAIL${NC}: $testname (compilation error)"
            failed=$((failed + 1))
        fi
        
        # Clean up temporary test file
        rm -f "$testname"
    fi
done

echo ""
echo "=========================================="
echo "Summary: Passed: $passed Failed: $failed Total: $total"
echo "=========================================="

if [ $failed -eq 0 ] && [ $total -gt 0 ]; then
    exit 0
else
    exit 1
fi
