#!/bin/bash

# Script to compare RTL output between new compiler and expected RTL files
# This script compares the RTL files generated by the new-compiler
# with expected RTL files from the reference SCLP compiler

set -e  # Exit on any error

# Define compiler paths
NEW_COMPILER="./new-compiler"
EXPECTED_DIR="example-programs/Level-4-valid-rtl"
TEST_DIR="example-programs/Level-4-test-cases"

# Check if new compiler exists
if [ ! -f "$NEW_COMPILER" ]; then
    echo "Error: $NEW_COMPILER not found. Please compile it first."
    exit 1
fi

# Initialize counters
passed=0
failed=0
total=0

# Color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "=========================================="
echo "RTL Comparison Test Suite"
echo "=========================================="
echo ""

# Process all Level-4 test cases
# Process all Level-4 test cases
for testfile in "$TEST_DIR"/l4-exmp*.c; do
    if [ -f "$testfile" ]; then
        testname=$(basename "$testfile")
        base_testname="${testname%.c}"
        
        total=$((total + 1))
        
        echo -n "Testing $testname ... "
        
        # Run the new compiler directly on the file in its original location
        # Most compilers output the .rtl file in the same directory as the source
        if "$NEW_COMPILER" "$testfile" --show-rtl > /dev/null 2>&1; then
            
            # Path to the generated RTL file
            generated_rtl="$TEST_DIR/${base_testname}.c.rtl"
            
            if [ -f "$generated_rtl" ]; then
                # Match the expected file name (using your naming convention)
                expected_file="$EXPECTED_DIR/${base_testname}.c.correct.rtl"
                
                if [ -f "$expected_file" ]; then
                    # Strip comments and trailing whitespace for a fair comparison
                    # <( ... ) is process substitution to avoid creating more temp files
                    if diff -Bw <(sed 's/;;.*//; s/[[:space:]]*$//' "$generated_rtl") \
                               <(sed 's/;;.*//; s/[[:space:]]*$//' "$expected_file") > /dev/null 2>&1; then
                        echo -e "${GREEN}✓ PASS${NC}"
                        passed=$((passed + 1))
                    else
                        echo -e "${RED}✗ FAIL${NC} (output differs)"
                        echo "----- DIFF for $testname -----"
                        diff -u -Bw \
                            <(sed 's/;;.*//; s/[[:space:]]*$//' "$expected_file") \
                            <(sed 's/;;.*//; s/[[:space:]]*$//' "$generated_rtl") || true
                        echo "------------------------------"
                        failed=$((failed + 1))
                    fi
                else
                    echo -e "${NC}○ SKIP${NC} (no expected file)"
                fi
            else
                echo -e "${RED}✗ FAIL${NC} (RTL not generated at $generated_rtl)"
                failed=$((failed + 1))
            fi
        else
            echo -e "${RED}✗ FAIL${NC} (compiler crashed)"
            failed=$((failed + 1))
        fi
    fi
done

echo ""
echo "=========================================="
echo "Summary: Passed: $passed Failed: $failed Total: $total"
echo "=========================================="

if [ $failed -eq 0 ] && [ $total -gt 0 ]; then
    exit 0
else
    exit 1
fi
