#!/bin/bash

# Script to compare ASM output between new compiler and expected ASM files
# This script compares the SPIM assembly files generated by the new-compiler
# with expected ASM files from the reference SCLP compiler

set -e  # Exit on any error

# Define compiler paths
NEW_COMPILER="./new-compiler"
EXPECTED_DIR="example-programs/Level-5-valid-asm"
TEST_DIR="example-programs/Level-5-test-cases"

# Check if new compiler exists
if [ ! -f "$NEW_COMPILER" ]; then
    echo "Error: $NEW_COMPILER not found. Please compile it first."
    exit 1
fi

# Initialize counters
passed=0
failed=0
total=0
skipped=0

# Color codes for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

echo "==========================================="
echo "ASM Comparison Test Suite (Level-5)"
echo "==========================================="
echo ""

# Process all Level-5 test cases
for testfile in "$TEST_DIR"/*.c; do
    if [ -f "$testfile" ]; then
        testname=$(basename "$testfile")
        base_testname="${testname%.c}"
        
        total=$((total + 1))
        
        echo -n "Testing $testname ... "
        
        # Run the new compiler directly on the file in its original location
        if "$NEW_COMPILER" "$testfile" --show-asm > /dev/null 2>&1; then
            
            # Path to the generated ASM file
            generated_asm="$TEST_DIR/${base_testname}.c.spim"
            
            if [ -f "$generated_asm" ]; then
                # Match the expected file name
                expected_file="$EXPECTED_DIR/${base_testname}.c.correct.spim"
                
                if [ -f "$expected_file" ]; then
                    # Strip comments (everything after #) and trailing whitespace for fair comparison
                    # Use diff -Bw to ignore blank lines and whitespace differences
                    if diff -Bw <(sed 's/#.*//; s/[[:space:]]*$//' "$generated_asm") \
                               <(sed 's/#.*//; s/[[:space:]]*$//' "$expected_file") > /dev/null 2>&1; then
                        echo -e "${GREEN}✓ PASS${NC}"
                        passed=$((passed + 1))
                    else
                        echo -e "${RED}✗ FAIL${NC} (output differs)"
                        echo "--- Difference in $testname ---"
                        diff -u -Bw \
                            <(sed 's/#.*//; s/[[:space:]]*$//' "$expected_file") \
                            <(sed 's/#.*//; s/[[:space:]]*$//' "$generated_asm") || true
                        echo "----------------------------------------"
                        failed=$((failed + 1))
                    fi
                else
                    echo -e "${YELLOW}○ SKIP${NC} (no expected file)"
                    skipped=$((skipped + 1))
                fi
            else
                echo -e "${RED}✗ FAIL${NC} (ASM not generated at $generated_asm)"
                failed=$((failed + 1))
            fi
        else
            echo -e "${RED}✗ FAIL${NC} (compiler crashed)"
            failed=$((failed + 1))
        fi
    fi
done

echo ""
echo "==========================================="
echo "Summary: Passed: $passed Failed: $failed Skipped: $skipped Total: $total"
echo "==========================================="

if [ $failed -eq 0 ] && [ $total -gt 0 ]; then
    exit 0
else
    exit 1
fi
